name: data_agent
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - numpy=1.26.4
  - pandas=2.1.4
  - matplotlib=3.8.2
  - seaborn=0.12.2
  - flask=2.3.3
  - pip
  - pip:
    - torch==2.1.2
    - transformers==4.35.2
    - faiss-cpu==1.7.4
    - flask-restful==0.3.10
    - pymysql==1.1.0
    - flask-sqlalchemy==3.1.1s
    - flask-cors==4.0.0
    - python-dotenv==1.0.0
    - requests==2.31.0
    - beautifulsoup4==4.12.2
    - fastapi==0.104.1
    - uvicorn==0.24.0
    - pydantic==2.5.2
    - openai==1.3.5  # 添加OpenAI库